//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Northwind
{
	/// <summary>Class which represents the entity 'Category'.</summary>
	public partial class Category : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();

		/// <summary>Initializes a new instance of the <see cref="Category"/> class.</summary>
		public Category() : base()
		{
			this.Products = new List<Product>();
			OnCreated();
		}

		/// <summary>Gets or sets the CategoryId field. </summary>
		public System.Int32 CategoryId { get; set;}
		/// <summary>Gets or sets the CategoryName field. </summary>
		public System.String CategoryName { get; set;}
		/// <summary>Gets or sets the Description field. </summary>
		public System.String Description { get; set;}
		/// <summary>Gets or sets the Picture field. </summary>
		public System.Byte[] Picture { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'Product.Category - Category.Products (m:1)'</summary>
		public virtual List<Product> Products { get; set;}
	}
}
