//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Northwind
{
	/// <summary>Class which represents the entity 'Customer'.</summary>
	public partial class Customer : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();

		/// <summary>Initializes a new instance of the <see cref="Customer"/> class.</summary>
		public Customer() : base()
		{
			this.CustomerCustomerDemos = new List<CustomerCustomerDemo>();
			this.Orders = new List<Order>();
			OnCreated();
		}

		/// <summary>Gets or sets the Address field. </summary>
		public System.String Address { get; set;}
		/// <summary>Gets or sets the City field. </summary>
		public System.String City { get; set;}
		/// <summary>Gets or sets the CompanyName field. </summary>
		public System.String CompanyName { get; set;}
		/// <summary>Gets or sets the ContactName field. </summary>
		public System.String ContactName { get; set;}
		/// <summary>Gets or sets the ContactTitle field. </summary>
		public System.String ContactTitle { get; set;}
		/// <summary>Gets or sets the Country field. </summary>
		public System.String Country { get; set;}
		/// <summary>Gets or sets the CustomerId field. </summary>
		public System.String CustomerId { get; set;}
		/// <summary>Gets or sets the Fax field. </summary>
		public System.String Fax { get; set;}
		/// <summary>Gets or sets the Phone field. </summary>
		public System.String Phone { get; set;}
		/// <summary>Gets or sets the PostalCode field. </summary>
		public System.String PostalCode { get; set;}
		/// <summary>Gets or sets the Region field. </summary>
		public System.String Region { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'CustomerCustomerDemo.Customer - Customer.CustomerCustomerDemos (m:1)'</summary>
		public virtual List<CustomerCustomerDemo> CustomerCustomerDemos { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'Order.Customer - Customer.Orders (m:1)'</summary>
		public virtual List<Order> Orders { get; set;}
	}
}
