//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Northwind
{
	/// <summary>Class which represents the entity 'EmployeeTerritory'.</summary>
	public partial class EmployeeTerritory : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();

		/// <summary>Initializes a new instance of the <see cref="EmployeeTerritory"/> class.</summary>
		public EmployeeTerritory() : base()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the EmployeeId field. </summary>
		public System.Int32 EmployeeId { get; set;}
		/// <summary>Gets or sets the TerritoryId field. </summary>
		public System.String TerritoryId { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'EmployeeTerritory.Employee - Employee.EmployeeTerritories (m:1)'</summary>
		public virtual Employee Employee { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'EmployeeTerritory.Territory - Territory.EmployeeTerritories (m:1)'</summary>
		public virtual Territory Territory { get; set;}
	}
}
