//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Northwind
{
	/// <summary>Class which represents the entity 'Order'.</summary>
	public partial class Order : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();

		/// <summary>Initializes a new instance of the <see cref="Order"/> class.</summary>
		public Order() : base()
		{
			this.OrderDetails = new List<OrderDetail>();
			OnCreated();
		}

		/// <summary>Gets or sets the CustomerId field. </summary>
		public System.String CustomerId { get; set;}
		/// <summary>Gets or sets the EmployeeId field. </summary>
		public Nullable<System.Int32> EmployeeId { get; set;}
		/// <summary>Gets or sets the Freight field. </summary>
		public Nullable<System.Decimal> Freight { get; set;}
		/// <summary>Gets or sets the OrderDate field. </summary>
		public Nullable<System.DateTime> OrderDate { get; set;}
		/// <summary>Gets or sets the OrderId field. </summary>
		public System.Int32 OrderId { get; set;}
		/// <summary>Gets or sets the RequiredDate field. </summary>
		public Nullable<System.DateTime> RequiredDate { get; set;}
		/// <summary>Gets or sets the ShipAddress field. </summary>
		public System.String ShipAddress { get; set;}
		/// <summary>Gets or sets the ShipCity field. </summary>
		public System.String ShipCity { get; set;}
		/// <summary>Gets or sets the ShipCountry field. </summary>
		public System.String ShipCountry { get; set;}
		/// <summary>Gets or sets the ShipName field. </summary>
		public System.String ShipName { get; set;}
		/// <summary>Gets or sets the ShippedDate field. </summary>
		public Nullable<System.DateTime> ShippedDate { get; set;}
		/// <summary>Gets or sets the ShipPostalCode field. </summary>
		public System.String ShipPostalCode { get; set;}
		/// <summary>Gets or sets the ShipRegion field. </summary>
		public System.String ShipRegion { get; set;}
		/// <summary>Gets or sets the ShipVia field. </summary>
		public Nullable<System.Int32> ShipVia { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'Order.Customer - Customer.Orders (m:1)'</summary>
		public virtual Customer Customer { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'Order.Employee - Employee.Orders (m:1)'</summary>
		public virtual Employee Employee { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'OrderDetail.Order - Order.OrderDetails (m:1)'</summary>
		public virtual List<OrderDetail> OrderDetails { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'Order.Shipper - Shipper.Orders (m:1)'</summary>
		public virtual Shipper Shipper { get; set;}
	}
}
