//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Northwind
{
	/// <summary>Class which represents the entity 'CustomerDemographic'.</summary>
	public partial class CustomerDemographic : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();

		/// <summary>Initializes a new instance of the <see cref="CustomerDemographic"/> class.</summary>
		public CustomerDemographic() : base()
		{
			this.CustomerCustomerDemos = new List<CustomerCustomerDemo>();
			OnCreated();
		}

		/// <summary>Gets or sets the CustomerDesc field. </summary>
		public System.String CustomerDesc { get; set;}
		/// <summary>Gets or sets the CustomerTypeId field. </summary>
		public System.String CustomerTypeId { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'CustomerCustomerDemo.CustomerDemographic - CustomerDemographic.CustomerCustomerDemos (m:1)'</summary>
		public virtual List<CustomerCustomerDemo> CustomerCustomerDemos { get; set;}
	}
}
