//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Northwind
{
	/// <summary>Class which represents the entity 'CustomerCustomerDemo'.</summary>
	public partial class CustomerCustomerDemo : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();

		/// <summary>Initializes a new instance of the <see cref="CustomerCustomerDemo"/> class.</summary>
		public CustomerCustomerDemo() : base()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the CustomerId field. </summary>
		public System.String CustomerId { get; set;}
		/// <summary>Gets or sets the CustomerTypeId field. </summary>
		public System.String CustomerTypeId { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'CustomerCustomerDemo.Customer - Customer.CustomerCustomerDemos (m:1)'</summary>
		public virtual Customer Customer { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'CustomerCustomerDemo.CustomerDemographic - CustomerDemographic.CustomerCustomerDemos (m:1)'</summary>
		public virtual CustomerDemographic CustomerDemographic { get; set;}
	}
}
