//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Northwind
{
	/// <summary>Class which represents the entity 'Employee'.</summary>
	public partial class Employee : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();

		/// <summary>Initializes a new instance of the <see cref="Employee"/> class.</summary>
		public Employee() : base()
		{
			this.EmployeeTerritories = new List<EmployeeTerritory>();
			this.Orders = new List<Order>();
			OnCreated();
		}

		/// <summary>Gets or sets the Address field. </summary>
		public System.String Address { get; set;}
		/// <summary>Gets or sets the BirthDate field. </summary>
		public Nullable<System.DateTime> BirthDate { get; set;}
		/// <summary>Gets or sets the City field. </summary>
		public System.String City { get; set;}
		/// <summary>Gets or sets the Country field. </summary>
		public System.String Country { get; set;}
		/// <summary>Gets or sets the EmployeeId field. </summary>
		public System.Int32 EmployeeId { get; set;}
		/// <summary>Gets or sets the Extension field. </summary>
		public System.String Extension { get; set;}
		/// <summary>Gets or sets the FirstName field. </summary>
		public System.String FirstName { get; set;}
		/// <summary>Gets or sets the HireDate field. </summary>
		public Nullable<System.DateTime> HireDate { get; set;}
		/// <summary>Gets or sets the HomePhone field. </summary>
		public System.String HomePhone { get; set;}
		/// <summary>Gets or sets the LastName field. </summary>
		public System.String LastName { get; set;}
		/// <summary>Gets or sets the Notes field. </summary>
		public System.String Notes { get; set;}
		/// <summary>Gets or sets the Photo field. </summary>
		public System.Byte[] Photo { get; set;}
		/// <summary>Gets or sets the PhotoPath field. </summary>
		public System.String PhotoPath { get; set;}
		/// <summary>Gets or sets the PostalCode field. </summary>
		public System.String PostalCode { get; set;}
		/// <summary>Gets or sets the Region field. </summary>
		public System.String Region { get; set;}
		/// <summary>Gets or sets the ReportsTo field. </summary>
		public Nullable<System.Int32> ReportsTo { get; set;}
		/// <summary>Gets or sets the Title field. </summary>
		public System.String Title { get; set;}
		/// <summary>Gets or sets the TitleOfCourtesy field. </summary>
		public System.String TitleOfCourtesy { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'EmployeeTerritory.Employee - Employee.EmployeeTerritories (m:1)'</summary>
		public virtual List<EmployeeTerritory> EmployeeTerritories { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'Order.Employee - Employee.Orders (m:1)'</summary>
		public virtual List<Order> Orders { get; set;}
	}
}
