//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Northwind
{
	/// <summary>Class which represents the entity 'Product'.</summary>
	public partial class Product : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();

		/// <summary>Initializes a new instance of the <see cref="Product"/> class.</summary>
		public Product() : base()
		{
			this.OrderDetails = new List<OrderDetail>();
			OnCreated();
		}

		/// <summary>Gets or sets the CategoryId field. </summary>
		public Nullable<System.Int32> CategoryId { get; set;}
		/// <summary>Gets or sets the Discontinued field. </summary>
		public System.Boolean Discontinued { get; set;}
		/// <summary>Gets or sets the ProductId field. </summary>
		public System.Int32 ProductId { get; set;}
		/// <summary>Gets or sets the ProductName field. </summary>
		public System.String ProductName { get; set;}
		/// <summary>Gets or sets the QuantityPerUnit field. </summary>
		public System.String QuantityPerUnit { get; set;}
		/// <summary>Gets or sets the ReorderLevel field. </summary>
		public Nullable<System.Int16> ReorderLevel { get; set;}
		/// <summary>Gets or sets the SupplierId field. </summary>
		public Nullable<System.Int32> SupplierId { get; set;}
		/// <summary>Gets or sets the UnitPrice field. </summary>
		public Nullable<System.Decimal> UnitPrice { get; set;}
		/// <summary>Gets or sets the UnitsInStock field. </summary>
		public Nullable<System.Int16> UnitsInStock { get; set;}
		/// <summary>Gets or sets the UnitsOnOrder field. </summary>
		public Nullable<System.Int16> UnitsOnOrder { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'Product.Category - Category.Products (m:1)'</summary>
		public virtual Category Category { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'OrderDetail.Product - Product.OrderDetails (m:1)'</summary>
		public virtual List<OrderDetail> OrderDetails { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'Product.Supplier - Supplier.Products (m:1)'</summary>
		public virtual Supplier Supplier { get; set;}
	}
}
