//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Northwind
{
	/// <summary>Class which represents the entity 'Region'.</summary>
	public partial class Region : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();

		/// <summary>Initializes a new instance of the <see cref="Region"/> class.</summary>
		public Region() : base()
		{
			this.Territories = new List<Territory>();
			OnCreated();
		}

		/// <summary>Gets or sets the RegionDescription field. </summary>
		public System.String RegionDescription { get; set;}
		/// <summary>Gets or sets the RegionId field. </summary>
		public System.Int32 RegionId { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'Territory.Region - Region.Territories (m:1)'</summary>
		public virtual List<Territory> Territories { get; set;}
	}
}
