//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Northwind
{
	/// <summary>Class which represents the entity 'Supplier'.</summary>
	public partial class Supplier : CommonEntityBase
	{
		/// <summary>Method called from the constructor</summary>
		partial void OnCreated();

		/// <summary>Initializes a new instance of the <see cref="Supplier"/> class.</summary>
		public Supplier() : base()
		{
			this.Products = new List<Product>();
			OnCreated();
		}

		/// <summary>Gets or sets the Address field. </summary>
		public System.String Address { get; set;}
		/// <summary>Gets or sets the City field. </summary>
		public System.String City { get; set;}
		/// <summary>Gets or sets the CompanyName field. </summary>
		public System.String CompanyName { get; set;}
		/// <summary>Gets or sets the ContactName field. </summary>
		public System.String ContactName { get; set;}
		/// <summary>Gets or sets the ContactTitle field. </summary>
		public System.String ContactTitle { get; set;}
		/// <summary>Gets or sets the Country field. </summary>
		public System.String Country { get; set;}
		/// <summary>Gets or sets the Fax field. </summary>
		public System.String Fax { get; set;}
		/// <summary>Gets or sets the HomePage field. </summary>
		public System.String HomePage { get; set;}
		/// <summary>Gets or sets the Phone field. </summary>
		public System.String Phone { get; set;}
		/// <summary>Gets or sets the PostalCode field. </summary>
		public System.String PostalCode { get; set;}
		/// <summary>Gets or sets the Region field. </summary>
		public System.String Region { get; set;}
		/// <summary>Gets or sets the SupplierId field. </summary>
		public System.Int32 SupplierId { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'Product.Supplier - Supplier.Products (m:1)'</summary>
		public virtual List<Product> Products { get; set;}
	}
}
